Add locale as named arguement
jens-chorus/audio-add-title pull request #2
Opened 2023-08-03 20:55 UTC by jens-chorus

mhh, wir müssen mal unsere IDEs bzgl. Formatting für bash allignen denke ich...

2023-08-06 12:17 UTC, kallekruse requested changes

2023-08-06 12:17 UTC, kallekruse commented on convert-to-title.sh
> +printf "locale: $locale\n"
Zur besseren Übersicht würde ich im oberen Bereich der Datei Konstanten und Funktionen definieren und erst danach die 'main-Methode' beginnen lassen. Also Zeilen 3-13 entweder in eine Funktion verpacken oder an Zeile 44 verschieben.

2023-08-06 12:17 UTC, kallekruse commented on convert-to-title.sh
> +if [ -z ${locale+x} ]; then
was macht das `+x`?

2023-08-06 12:17 UTC, kallekruse commented on convert-to-title.sh
> +done
Offene Frage: Sollen wir den locale-Parameter validieren, also nur ausgewählte Werte akzeptieren?

2023-08-07 17:42 UTC, jens-chorus commented on convert-to-title.sh
> +done
Fände ich sinnvoll. Oder einfach valide locales nach xy_XY - Aber in einem separaten feature branch

2023-08-07 17:42 UTC, jens-chorus commented on convert-to-title.sh
> +if [ -z ${locale+x} ]; then
Google sagt, dass ist gut und es tut was es soll zum zu verifzieren, dass der Parameter gesetzt ist und kein empty string ist.

2023-08-07 17:42 UTC, jens-chorus commented on convert-to-title.sh
> +printf "locale: $locale\n"
done

2023-08-07 17:43 UTC, merged